Controllers/BasketController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using DAL.DAO;
using DAL.Models;
using WebShop.DTO;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebShop.Models;

namespace WebShop.Controllers
{
    public class BasketController : Controller
    {
        private readonly BasketDAO _basketDAO;
        private readonly ProductDAO _productDAO;

        public BasketController(BasketDAO basketDAO, ProductDAO productDAO)
        {
            _basketDAO = basketDAO;
            _productDAO = productDAO;
        }

        // GET: Basket/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Basket/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(DAL.Models.Basket basket)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    basket.CreatedAt = DateTime.Now;
                    int basketId = _basketDAO.AddBasket(basket);

                    // Redirect to ProductLine creation for the basket, passing the Basket ID
                    return RedirectToAction("CreateForBasket", "ProductLine", new { basketId = basketId });
                }
                catch (Exception ex)
                {
                    // Log error and show an error view
                    Console.WriteLine($"Error creating basket: {ex.Message}");
                    ModelState.AddModelError("", "An error occurred while creating the basket. Please try again.");
                }
            }

            // If the model state is invalid or an error occurs, return to the create view
            return View(basket);
        }

        // GET: Basket/Success
        public IActionResult Success()
        {
            return View();
        }
    }
}















Controllers/DeliveryController.cs
using DAL.DAO;
using DAL.Models;
using Microsoft.AspNetCore.Mvc;

namespace WebShop.Controllers
{
    public class DeliveryController : Controller
    {
        private readonly DeliveryDAO _deliveryDAO;

        public DeliveryController(DeliveryDAO deliveryDAO)
        {
            _deliveryDAO = deliveryDAO;
        }

        // GET: Delivery/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Delivery/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(DAL.Models.Delivery delivery)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    int deliveryId = _deliveryDAO.AddOrder(delivery);

                    // Redirect to ProductLine creation, passing the Delivery ID
                    return RedirectToAction("Create", "ProductLine", new { deliveryId = deliveryId });
                }
                catch (Exception ex)
                {
                    // Log error and show an error view
                    Console.WriteLine($"Error adding delivery: {ex.Message}");
                    ModelState.AddModelError("", "An error occurred while adding the delivery. Please try again.");
                }
            }

            // If the model state is invalid or an error occurs, return to the create view
            return View(delivery);
        }
    }
}





Controllers/ProductController.cs
using DAL.DAO;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using DAL.Models;
using WebShop.DTO;

namespace WebShop.Controllers
{
    public class ProductController : Controller
    {
        private ProductDAO _productDAO;

        public ProductController(ProductDAO productDAO)
        {
            _productDAO = productDAO;
        }

        public ActionResult Create()
        {
            return View(new Product());
        }

        [HttpPost]
        public ActionResult Create(Product product)
        {
            try
            {
                if (!ModelState.IsValid) { throw new InvalidDataException(); }
                _productDAO.AddProduct(product);
                return RedirectToAction("Details");
            }
            catch { return View(); }
        }

        public IActionResult Details()
        {
            IEnumerable<Product> products = _productDAO.GetAllProducts();
            return View(products);
        }


    }

}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebShop.styles.css" asp-append-version="true" />
    @await RenderSectionAsync("Styles", required: false)  <!-- Ensure this line is present -->
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebShop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Details">Product</a>
                        </li>

                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Basket" asp-action="Index">Basket</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Basket" asp-action="Create">Make a basket</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Delivery" asp-action="Create">Make an order</a>
                            </li>
                        }

                        <!-- Authentication Links -->
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <form asp-controller="Account" asp-action="Logout" method="post" class="form-inline">
                                    <button type="submit" class="btn btn-link nav-link text-dark">Logout</button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Create">Register</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WebShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

